const mediaUrl = (relativePath) => `/api/media?path=${encodeURIComponent(`soccer_input_dataset/outputs/${relativePath}`)}`;

export const analysisLevelLabels = {
  L1: "关键事件",
  L2: "数据统计",
  L3: "进攻组织",
  L4: "队形空间",
};

export const demoAssets = [
  {
    id:"test5-formation-focus",title:"五分钟阵型可视化复盘",filename:"test_5min_boxes.mp4",
    createdAt:"2026-10-06",duration:299.9,size:"86.2 MB",status:"分析完成",
    poster:mediaUrl("test_5min_formation_focus/formation_01/distribution.jpg"),
    src:mediaUrl("test_5min_layered_v2/test_5min_boxes.mp4"),
    resultEndpoint:"/api/demo-results/test5-formation-focus",boxesOnly:true,eventCount:18,
    tags:["足球","阵型分布","证据短片"],
  },
  {
    id: "test5-player-focus", title: "五分钟球员编号与个人复盘", filename: "test_5min_boxes.mp4",
    createdAt: "2026-10-06", duration: 299.9, size: "86.2 MB", status: "分析完成",
    poster: mediaUrl("test_5min_layered_v2/boxes_raw_frame6241.jpg"),
    src: mediaUrl("test_5min_layered_v2/test_5min_boxes.mp4"),
    resultEndpoint: "/api/demo-results/test5-player-focus", boxesOnly: true, eventCount: 18,
    tags: ["足球", "球员编号", "个人复盘"],
  },
  {
    id: "test5-openai-v1", title: "五分钟智能视觉复盘", filename: "test_5min_boxes.mp4",
    createdAt: "2026-09-30", duration: 299.9, size: "86.2 MB", status: "分析完成",
    poster: mediaUrl("test_5min_layered_v2/boxes_raw_frame6241.jpg"),
    src: mediaUrl("test_5min_layered_v2/test_5min_boxes.mp4"),
    resultEndpoint: "/api/demo-results/test5-openai-v1", boxesOnly: true, eventCount: 25,
    tags: ["足球", "时序复核", "战术评语"],
  },
  {
    id: "test5-layered-v4", title: "五分钟战术深度复盘", filename: "test_5min_boxes.mp4",
    createdAt: "2026-09-22", duration: 299.9, size: "86.2 MB", status: "分析完成",
    poster: mediaUrl("test_5min_layered_v2/boxes_raw_frame6241.jpg"),
    src: mediaUrl("test_5min_layered_v2/test_5min_boxes.mp4"),
    resultEndpoint: "/api/demo-results/test5-layered-v4", boxesOnly: true, eventCount: 18,
    tags: ["足球", "组织与空间", "战术评语"],
  },
  {
    id: "test5-assistant-v3",
    title: "五分钟助手切片复核版",
    filename: "test_5min_assistant_review.mp4",
    createdAt: "2026-09-20",
    duration: 299.9,
    size: "86.2 MB",
    status: "分析完成",
    poster: mediaUrl("test_5min_layered_v2/boxes_raw_frame6241.jpg"),
    src: mediaUrl("test_5min_assistant_review_v3/test_5min_assistant_review.mp4"),
    resultEndpoint: "/api/demo-results/test5-assistant-v3",
    boxesOnly: true,
    eventCount: 18,
    tags: ["足球", "助手复核", "对照测试"],
  },
  {
    id: "test5-layered-v2",
    title: "五分钟分层技战术分析",
    filename: "test_5min_boxes.mp4",
    createdAt: "2026-09-20",
    duration: 299.9,
    size: "86.2 MB",
    status: "分析完成",
    poster: mediaUrl("test_5min_layered_v2/boxes_raw_frame6241.jpg"),
    src: mediaUrl("test_5min_layered_v2/test_5min_boxes.mp4"),
    resultEndpoint: "/api/demo-results/test5-layered-v2",
    boxesOnly: true,
    eventCount: 17,
    tags: ["足球", "分层分析", "多帧审核"],
  },
  {
    id: "test5-dense-vision-v1",
    title: "五分钟多帧视觉复核测试",
    filename: "test_5min_dense_vision.mp4",
    createdAt: "2026-09-20 20:07",
    duration: 299.8,
    size: "64.2 MB",
    status: "分析完成",
    poster: mediaUrl("test_5min_dense_vision_v1/test_5min_dense_vision_poster.jpg"),
    src: mediaUrl("test_5min_dense_vision_v1/test_5min_dense_vision.mp4"),
    resultEndpoint: "/api/demo-results/test5-dense-vision-v1",
    eventCount: 8,
    tags: ["足球", "多帧视觉复核", "技战术候选"],
  },
  {
    id: "full-pitch-ball-60s",
    title: "双机位足球与队形复盘",
    filename: "分析视频2.mp4",
    createdAt: "2026-09-20 14:00",
    duration: 60,
    size: "8.6 MB",
    status: "分析完成",
    poster: `/api/media?path=${encodeURIComponent("二维分析/分析视频2_封面.jpg")}`,
    src: `/api/media?path=${encodeURIComponent("二维分析/分析视频2.mp4")}`,
    analysisSrc: `/api/media?path=${encodeURIComponent("二维分析/分析视频2_技战术结果/分析视频2_全景技战术.mp4")}`,
    analysisPoster: `/api/media?path=${encodeURIComponent("二维分析/分析视频2_技战术结果/分析视频2_全景技战术_封面.jpg")}`,
    focusPreviewSrc: `/api/media?path=${encodeURIComponent("二维分析/分析视频2_技战术结果/分析视频2_主机位预览.mp4")}`,
    cameraLayout: "two-cameras-plus-pitch",
    resultEndpoint: "/api/demo-results/full-pitch-ball-60s",
    eventCount: 6,
    tags: ["足球", "关键事件", "二维空间", "球轨迹", "双机位"],
  },
  {
    id: "test5-corner-review-v2",
    title: "五分钟定位球候选复核（修正版）",
    filename: "test_5min_vision_review_v2.mp4",
    createdAt: "2026-09-19 18:00",
    duration: 299.8,
    size: "64.2 MB",
    status: "分析完成",
    poster: mediaUrl("test_5min_corner_review_v2/test_5min_vision_review_v2_poster.jpg"),
    src: mediaUrl("test_5min_corner_review_v2/test_5min_vision_review_v2.mp4"),
    eventCount: 2,
    previewOnly: true,
    tags: ["足球", "视觉复核", "待人工确认"],
  },
  {
    id: "full-pitch-spatial-60s",
    title: "双机位二维空间分析",
    filename: "分析视频.mp4",
    createdAt: "2026-09-19 16:30",
    duration: 60,
    size: "1.7 MB",
    status: "分析完成",
    poster: `/api/media?path=${encodeURIComponent("二维分析/空间分析封面.jpg")}`,
    src: `/api/media?path=${encodeURIComponent("二维分析/分析视频.mp4")}`,
    resultEndpoint: "/api/demo-results/full-pitch-spatial-60s",
    eventCount: 12,
    tags: ["足球", "二维空间", "双机位"],
  },
  {
    id: "soccernet-mu-lei-40m",
    title: "SoccerNet 40分钟长视频测试",
    filename: "SoccerNet_ManUtd_Leicester_1H_00m-40m_720p.mp4",
    createdAt: "2026-09-09 22:37",
    duration: 2400.2,
    size: "489.7 MB",
    status: "分析完成",
    poster: mediaUrl("SoccerNet_MU_LEI_40min_v1/02_tactical_red_blue_v2_frame58501.jpg"),
    src: mediaUrl("SoccerNet_MU_LEI_40min_v1/03_tactical_red_blue_v2_web.mp4"),
    resultEndpoint: "/api/demo-results/soccernet-mu-lei-40m",
    eventCount: 111,
    tags: ["足球", "长视频分析", "SoccerNet"],
  },
  {
    id: "match-overview",
    title: "五分钟比赛技战术分析",
    filename: "test_5min_tactical_base.mp4",
    createdAt: "2026-09-03 10:24",
    duration: 300,
    size: "343.9 MB",
    status: "分析完成",
    poster: mediaUrl("test_5min_tactical_visualized_frame4500.jpg"),
    src: mediaUrl("test_5min_current/test_5min_tactical_base_web.mp4"),
    tags: ["足球", "整体分析"],
  },
  {
    id: "offensive-analysis",
    title: "进攻组织与射门分析",
    filename: "test_30s_offensive_analysis_zh.mp4",
    createdAt: "2026-09-01 18:42",
    duration: 30,
    size: "32.5 MB",
    status: "分析完成",
    poster: mediaUrl("test_30s_offensive_analysis_zh_frame300.jpg"),
    src: mediaUrl("test_30s_offensive_analysis_zh_web.mp4"),
    tags: ["足球", "进攻分析"],
  },
  {
    id: "individual-technique",
    title: "射门个人技术分析",
    filename: "goal_closeup_individual_technique_zh_bestshot.mp4",
    createdAt: "2026-08-29 15:16",
    duration: 28,
    size: "18.8 MB",
    status: "分析完成",
    poster: mediaUrl("goal_closeup_individual_technique_zh_bestshot_frame125.jpg"),
    src: mediaUrl("goal_closeup_individual_technique_zh_bestshot_web.mp4"),
    tags: ["足球", "个人动作"],
  },
  {
    id: "formation-analysis",
    title: "阵型与空间结构分析",
    filename: "test_30s_formation_clean_board_smoke.mp4",
    createdAt: "2026-08-28 09:35",
    duration: 30,
    size: "36.7 MB",
    status: "分析完成",
    poster: mediaUrl("test_30s_formation_clean_board_smoke_frame300.jpg"),
    src: mediaUrl("test_30s_formation_clean_board_smoke_web.mp4"),
    tags: ["足球", "阵型分析"],
  },
];

export const demoProjects = [
  {id:"project-test5-formation-focus",title:"五分钟阵型可视化复盘",subtitle:"真实框连线 · 同镜头证据 · 审核统计",createdAt:"2026-10-06",assetIds:["test5-formation-focus"],type:"技战术分析"},
  { id: "project-test5-player-focus", title: "五分钟球员编号与个人复盘", subtitle: "临时编号 · 个人片段 · 画面复核", createdAt: "2026-10-06", assetIds: ["test5-player-focus"], type: "技战术分析" },
  { id: "project-test5-openai", title: "五分钟智能视觉复盘", subtitle: "时序审核 · 动态补证 · 门将复审", createdAt: "2026-09-30", assetIds: ["test5-openai-v1"], type: "技战术分析" },
  { id: "project-test5-depth", title: "五分钟战术深度复盘", subtitle: "事件 · 有球组织 · 局部空间 · 复盘评语", createdAt: "2026-09-22", assetIds: ["test5-layered-v4"], type: "技战术分析" },
  { id: "project-test5-assistant", title: "五分钟助手复核对照测试", subtitle: "原候选与助手意见对照 · 非专家标注", createdAt: "2026-09-20", assetIds: ["test5-assistant-v3"], type: "技战术分析" },
  {
    id: "project-test5-layered",
    title: "五分钟分层技战术复盘",
    subtitle: "检测框原片 · 多帧审核 · 进攻组织",
    createdAt: "2026-09-20",
    assetIds: ["test5-layered-v2"],
    type: "技战术分析",
  },
  {
    id: "project-test5-dense-vision",
    title: "五分钟多帧视觉复核",
    subtitle: "蓝队 vs 白队 · 8个分布式候选节点",
    createdAt: "2026-09-20 20:07",
    assetIds: ["test5-dense-vision-v1"],
    type: "技战术分析",
  },
  {
    id: "project-full-pitch-ball",
    title: "双机位足球与队形复盘",
    subtitle: "红队 vs 蓝队 · 原画面 + 球场投影",
    createdAt: "2026-09-20 14:00",
    assetIds: ["full-pitch-ball-60s"],
    type: "技战术分析",
  },
  {
    id: "project-full-pitch-spatial",
    title: "双机位全场空间结构复盘",
    subtitle: "红队 vs 蓝队 · 60秒俯视轨迹",
    createdAt: "2026-09-19 16:30",
    assetIds: ["full-pitch-spatial-60s"],
    type: "技战术分析",
  },
  {
    id: "project-soccernet-40m",
    title: "曼联 vs 莱斯特 40分钟技战术复盘",
    subtitle: "曼联红队 vs 莱斯特蓝队 · SoccerNet 720p",
    createdAt: "2026-09-09 22:40",
    assetIds: ["soccernet-mu-lei-40m"],
    type: "技战术分析",
  },
  {
    id: "project-main",
    title: "五分钟比赛技战术复盘",
    subtitle: "蓝队 vs 白队 · 视觉候选分析",
    createdAt: "2026-09-03 10:30",
    assetIds: ["match-overview", "offensive-analysis", "formation-analysis", "test5-corner-review-v2"],
    type: "技战术分析",
  },
  {
    id: "project-individual",
    title: "射门与门将个人技术",
    subtitle: "近景动作阶段与关键帧",
    createdAt: "2026-08-29 15:20",
    assetIds: ["individual-technique"],
    type: "个人技术",
  },
];

export const demoEvents = [
  {
    id: "event-touch",
    time: 12.13,
    end: 16.13,
    category: "传接带",
    group: "L1-03",
    type: "持球推进",
    title: "右队形成稳定持球推进",
    summary: "同一持球人在连续控制窗口内完成明确向前位移。",
    detail: "向前推进 8.4 米 · 持续 2.1 秒",
    confidence: 84,
    color: "green",
  },
  {
    id: "event-shot",
    time: 19.57,
    end: 23.57,
    category: "射门",
    group: "L1-01",
    type: "射门",
    title: "右队左侧通道射门候选",
    summary: "快速直接进攻结束于远距离射门，门前存在两名封堵球员。",
    detail: "距离 36.0 米 · 角度 10.6° · 球速 39.3 m/s",
    confidence: 96,
    color: "orange",
  },
  {
    id: "event-pass",
    time: 31,
    end: 34,
    category: "传接带",
    group: "L1-03",
    type: "传球",
    title: "同队持球人切换形成传球候选",
    summary: "足球完成有效位移并由同队球员稳定接收。",
    detail: "足球位移 14.2 米 · 结果 success",
    confidence: 90,
    color: "blue",
  },
  {
    id: "event-possession",
    time: 80.8,
    end: 84.8,
    category: "球权转换",
    group: "L1-04",
    type: "球权转换",
    title: "右队获得稳定球权",
    summary: "稳定控球状态跨队切换，形成丢失与夺回候选。",
    detail: "原控球队 左队 · 新控球队 右队",
    confidence: 82,
    color: "violet",
  },
  {
    id: "event-defense",
    time: 145.27,
    end: 149.27,
    category: "防守干预",
    group: "L1-05",
    type: "防守干预",
    title: "右队完成稳定夺回",
    summary: "根据跨队球权变化形成干预候选，具体动作需视频复核。",
    detail: "结果 possession_won · 子类型待确认",
    confidence: 90,
    color: "red",
  },
  {
    id: "event-goalkeeper",
    time: 208.03,
    end: 210.03,
    category: "门将事件",
    group: "L1-06",
    type: "门将控球",
    title: "门将持续接近并控制足球",
    summary: "二维球场中球门将距离由 11.9 米持续降至 0.3 米。",
    detail: "3:28.03 · 最近距离 0.27 米 · 稳定控制",
    confidence: 90,
    color: "violet",
  },
  {
    id: "event-set-piece",
    time: 239.17,
    end: 243.17,
    category: "定位球",
    group: "L1-02",
    subtype: "corner",
    type: "角球",
    title: "角球开出与落点候选",
    summary: "从角旗区开出并追踪至首次稳定控制位置。",
    detail: "运行 24.6 米 · 落入禁区 · 对方控制",
    confidence: 86,
    color: "yellow",
  },
  {
    id: "event-late-shot",
    time: 282.57,
    end: 286.57,
    category: "射门",
    group: "L1-01",
    type: "射门",
    title: "左队中路射门候选",
    summary: "连续推进后从中路完成终结，射门前防守压力较低。",
    detail: "禁区外 · 近侧防守 1 人 · xG 上下文代理 0.18",
    confidence: 78,
    color: "orange",
  },
];

export function buildGeneratedEvents(duration = 60) {
  const safeDuration = Math.max(duration || 60, 12);
  const templates = [
    [0.12, "传接带", "持球推进", "边路持球向前推进", "连续控制期间完成明显纵向位移。", "推进 8.6 米 · 持续 2.4 秒", 82, "green", "L1-03"],
    [0.27, "传接带", "传球", "同队稳定持球人发生切换", "足球完成有效位移并由同队球员稳定接收。", "传球候选 · 位移 12.3 米", 76, "blue", "L1-03"],
    [0.43, "球权转换", "球权转换", "稳定球权跨队切换", "原控球队失去控制，另一队形成稳定控球。", "结果待复核", 71, "cyan", "L1-04"],
    [0.62, "防守干预", "防守干预", "防守方完成球权夺回", "先输出统一干预大类，具体动作类型等待复核。", "结果 possession_won", 79, "red", "L1-05"],
    [0.81, "射门", "射门", "进攻三区高速向门轨迹", "足球速度和方向满足射门候选规则，需回看确认。", "射门结果 unknown", 74, "orange", "L1-01"],
  ];
  return templates.map((item, index) => ({
    id: `generated-${index}`,
    time: Math.min(safeDuration - 1, safeDuration * item[0]),
    end: Math.min(safeDuration, safeDuration * item[0] + 4),
    category: item[1],
    type: item[2],
    title: item[3],
    summary: item[4],
    detail: item[5],
    confidence: item[6],
    color: item[7],
    group: item[8],
  }));
}
